services:
  - type: web
    name: movie-recommendation
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --chdir /opt/render/project/src"
    plan: free
    envVars:
      - key: PORT
        value: 10000
